server:
  port: 8083

spring:
  application:
    name: merchant-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payflex
    username: payflex
    password: payflex
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/payflex
    user: payflex
    password: payflex
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.payflex.merchant: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

