server:
  port: ${PORT:8083}

spring:
  application:
    name: merchant-service

  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/payflex}
    username: ${PGUSER:payflex}
    password: ${PGPASSWORD:payflex}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  flyway:
    enabled: true
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/payflex}
    user: ${PGUSER:payflex}
    password: ${PGPASSWORD:payflex}
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.payflex.merchant: ${LOG_LEVEL:INFO}
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
