[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.build]
cmds = ["mvn clean package -DskipTests -pl api-gateway,auth-bff,merchant-service,payment-orchestrator -am"]

[start]
cmd = "echo 'Build completed. Use service-specific start command.'"
