server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_BFF_URL:http://localhost:8081}/.well-known/jwks.json
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: orchestrator
          uri: ${ORCHESTRATOR_URL:http://localhost:8082}
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

management:
  endpoints.web.exposure.include: health,info

logging:
  level:
    org.springframework.security: ${LOG_LEVEL:DEBUG}
    org.springframework.security.oauth2: ${LOG_LEVEL:DEBUG}
