server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

management:
  endpoints.web.exposure.include: health,info

# Redis (for idempotency demo) - optional if you run docker compose
spring:
  data:
    redis:
      host: localhost
      port: 6379
