[phases.setup]
nixPkgs = ["jdk21"]

[phases.install]
cmds = ["echo 'Using pre-installed Maven'"]

[phases.build]
cmds = ["cd .. && mvn clean package -DskipTests -pl auth-bff -am"]

[start]
cmd = "java -Dserver.port=$PORT ${JAVA_TOOL_OPTIONS:--XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Xmx512m} -jar target/auth-bff-1.0.0.jar"
