server:
  port: 8081

auth:
  issuer: https://auth.payflex.local
  audience: payflex-apis
  access-token-ttl-minutes: 10
  refresh-token-ttl-days: 30
  cookie:
    name: session
    domain: localhost
    secure: true
    sameSite: Lax
    httpOnly: true

pocketbase:
  url: http://localhost:8090
  collection: users
  merchantField: merchantId
  rolesField: roles

merchant:
  service:
    url: http://localhost:8083

management:
  endpoints.web.exposure.include: health,info
