server:
  port: ${PORT:8081}

auth:
  issuer: ${AUTH_ISSUER:https://auth.payflex.local}
  audience: payflex-apis
  access-token-ttl-minutes: 10
  refresh-token-ttl-days: 30
  cookie:
    name: session
    domain: ${COOKIE_DOMAIN:localhost}
    secure: ${COOKIE_SECURE:false}
    sameSite: Lax
    httpOnly: true

pocketbase:
  url: ${POCKETBASE_URL:http://localhost:8090}
  collection: users
  merchantField: merchantId
  rolesField: roles

merchant:
  service:
    url: ${MERCHANT_SERVICE_URL:http://localhost:8083}

management:
  endpoints.web.exposure.include: health,info

logging:
  level:
    com.payflex.auth: ${LOG_LEVEL:INFO}
