[phases.setup]
nixPkgs = ["jdk21"]

[phases.install]
cmds = ["echo 'Using pre-installed Maven'"]

[phases.build]
cmds = ["mvn clean package -DskipTests -pl merchant-service -am"]

[start]
cmd = "java -Dserver.port=$PORT $JAVA_TOOL_OPTIONS -jar merchant-service/target/merchant-service-1.0.0.jar"

