server:
  port: ${PORT:8082}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8081}/.well-known/jwks.json
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server.error.include-message: always
server.error.include-binding-errors: always

management:
  endpoints.web.exposure.include: health,info

logging:
  level:
    com.payflex.orchestrator: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    org.springframework.security.oauth2: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.springframework.http.codec: INFO
